/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as AppVocabularyRouteImport } from './routes/_app.vocabulary'
import { Route as AppStudioRouteImport } from './routes/_app.studio'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSongsIndexRouteImport } from './routes/_app.songs.index'
import { Route as AppDramasIndexRouteImport } from './routes/_app.dramas.index'
import { Route as AppCurriculumIndexRouteImport } from './routes/_app.curriculum.index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app.courses.index'
import { Route as ApiYoutubeConnectRouteImport } from './routes/api/youtube.connect'
import { Route as ApiYoutubeCallbackRouteImport } from './routes/api/youtube.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppVocabularyReviewRouteImport } from './routes/_app.vocabulary.review'
import { Route as AppSongsIdRouteImport } from './routes/_app.songs.$id'
import { Route as AppLessonsIdRouteImport } from './routes/_app.lessons.$id'
import { Route as AppDramasIdRouteImport } from './routes/_app.dramas.$id'
import { Route as AppCurriculumIdRouteImport } from './routes/_app.curriculum.$id'
import { Route as AppCoursesIdRouteImport } from './routes/_app.courses.$id'
import { Route as ApiPublicHooksReengagementPushRouteImport } from './routes/api/public/hooks/reengagement-push'
import { Route as ApiPublicHooksGenerateVideoRouteImport } from './routes/api/public/hooks/generate-video'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSongsIndexRoute = AppSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => AppRoute,
} as any)
const AppDramasIndexRoute = AppDramasIndexRouteImport.update({
  id: '/dramas/',
  path: '/dramas/',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumIndexRoute = AppCurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const ApiYoutubeConnectRoute = ApiYoutubeConnectRouteImport.update({
  id: '/api/youtube/connect',
  path: '/api/youtube/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeCallbackRoute = ApiYoutubeCallbackRouteImport.update({
  id: '/api/youtube/callback',
  path: '/api/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVocabularyReviewRoute = AppVocabularyReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppVocabularyRoute,
} as any)
const AppSongsIdRoute = AppSongsIdRouteImport.update({
  id: '/songs/$id',
  path: '/songs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsIdRoute = AppLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDramasIdRoute = AppDramasIdRouteImport.update({
  id: '/dramas/$id',
  path: '/dramas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculumIdRoute = AppCurriculumIdRouteImport.update({
  id: '/curriculum/$id',
  path: '/curriculum/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIdRoute = AppCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksReengagementPushRoute =
  ApiPublicHooksReengagementPushRouteImport.update({
    id: '/api/public/hooks/reengagement-push',
    path: '/api/public/hooks/reengagement-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateVideoRoute =
  ApiPublicHooksGenerateVideoRouteImport.update({
    id: '/api/public/hooks/generate-video',
    path: '/api/public/hooks/generate-video',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/students': typeof AppStudentsRoute
  '/studio': typeof AppStudioRoute
  '/vocabulary': typeof AppVocabularyRouteWithChildren
  '/media/$': typeof MediaSplatRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/curriculum/$id': typeof AppCurriculumIdRoute
  '/dramas/$id': typeof AppDramasIdRoute
  '/lessons/$id': typeof AppLessonsIdRoute
  '/songs/$id': typeof AppSongsIdRoute
  '/vocabulary/review': typeof AppVocabularyReviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/connect': typeof ApiYoutubeConnectRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/curriculum/': typeof AppCurriculumIndexRoute
  '/dramas/': typeof AppDramasIndexRoute
  '/songs/': typeof AppSongsIndexRoute
  '/api/public/hooks/generate-video': typeof ApiPublicHooksGenerateVideoRoute
  '/api/public/hooks/reengagement-push': typeof ApiPublicHooksReengagementPushRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/integrations': typeof AppIntegrationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/students': typeof AppStudentsRoute
  '/studio': typeof AppStudioRoute
  '/vocabulary': typeof AppVocabularyRouteWithChildren
  '/media/$': typeof MediaSplatRoute
  '/': typeof AppIndexRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/curriculum/$id': typeof AppCurriculumIdRoute
  '/dramas/$id': typeof AppDramasIdRoute
  '/lessons/$id': typeof AppLessonsIdRoute
  '/songs/$id': typeof AppSongsIdRoute
  '/vocabulary/review': typeof AppVocabularyReviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/connect': typeof ApiYoutubeConnectRoute
  '/courses': typeof AppCoursesIndexRoute
  '/curriculum': typeof AppCurriculumIndexRoute
  '/dramas': typeof AppDramasIndexRoute
  '/songs': typeof AppSongsIndexRoute
  '/api/public/hooks/generate-video': typeof ApiPublicHooksGenerateVideoRoute
  '/api/public/hooks/reengagement-push': typeof ApiPublicHooksReengagementPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/studio': typeof AppStudioRoute
  '/_app/vocabulary': typeof AppVocabularyRouteWithChildren
  '/media/$': typeof MediaSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/courses/$id': typeof AppCoursesIdRoute
  '/_app/curriculum/$id': typeof AppCurriculumIdRoute
  '/_app/dramas/$id': typeof AppDramasIdRoute
  '/_app/lessons/$id': typeof AppLessonsIdRoute
  '/_app/songs/$id': typeof AppSongsIdRoute
  '/_app/vocabulary/review': typeof AppVocabularyReviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
  '/api/youtube/connect': typeof ApiYoutubeConnectRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/curriculum/': typeof AppCurriculumIndexRoute
  '/_app/dramas/': typeof AppDramasIndexRoute
  '/_app/songs/': typeof AppSongsIndexRoute
  '/api/public/hooks/generate-video': typeof ApiPublicHooksGenerateVideoRoute
  '/api/public/hooks/reengagement-push': typeof ApiPublicHooksReengagementPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/integrations'
    | '/onboarding'
    | '/students'
    | '/studio'
    | '/vocabulary'
    | '/media/$'
    | '/courses/$id'
    | '/curriculum/$id'
    | '/dramas/$id'
    | '/lessons/$id'
    | '/songs/$id'
    | '/vocabulary/review'
    | '/api/auth/$'
    | '/api/youtube/callback'
    | '/api/youtube/connect'
    | '/courses/'
    | '/curriculum/'
    | '/dramas/'
    | '/songs/'
    | '/api/public/hooks/generate-video'
    | '/api/public/hooks/reengagement-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/integrations'
    | '/onboarding'
    | '/students'
    | '/studio'
    | '/vocabulary'
    | '/media/$'
    | '/'
    | '/courses/$id'
    | '/curriculum/$id'
    | '/dramas/$id'
    | '/lessons/$id'
    | '/songs/$id'
    | '/vocabulary/review'
    | '/api/auth/$'
    | '/api/youtube/callback'
    | '/api/youtube/connect'
    | '/courses'
    | '/curriculum'
    | '/dramas'
    | '/songs'
    | '/api/public/hooks/generate-video'
    | '/api/public/hooks/reengagement-push'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/integrations'
    | '/_app/onboarding'
    | '/_app/students'
    | '/_app/studio'
    | '/_app/vocabulary'
    | '/media/$'
    | '/_app/'
    | '/_app/courses/$id'
    | '/_app/curriculum/$id'
    | '/_app/dramas/$id'
    | '/_app/lessons/$id'
    | '/_app/songs/$id'
    | '/_app/vocabulary/review'
    | '/api/auth/$'
    | '/api/youtube/callback'
    | '/api/youtube/connect'
    | '/_app/courses/'
    | '/_app/curriculum/'
    | '/_app/dramas/'
    | '/_app/songs/'
    | '/api/public/hooks/generate-video'
    | '/api/public/hooks/reengagement-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiYoutubeCallbackRoute: typeof ApiYoutubeCallbackRoute
  ApiYoutubeConnectRoute: typeof ApiYoutubeConnectRoute
  ApiPublicHooksGenerateVideoRoute: typeof ApiPublicHooksGenerateVideoRoute
  ApiPublicHooksReengagementPushRoute: typeof ApiPublicHooksReengagementPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vocabulary': {
      id: '/_app/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/songs/': {
      id: '/_app/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof AppSongsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dramas/': {
      id: '/_app/dramas/'
      path: '/dramas'
      fullPath: '/dramas/'
      preLoaderRoute: typeof AppDramasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/': {
      id: '/_app/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof AppCurriculumIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/youtube/connect': {
      id: '/api/youtube/connect'
      path: '/api/youtube/connect'
      fullPath: '/api/youtube/connect'
      preLoaderRoute: typeof ApiYoutubeConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/callback': {
      id: '/api/youtube/callback'
      path: '/api/youtube/callback'
      fullPath: '/api/youtube/callback'
      preLoaderRoute: typeof ApiYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vocabulary/review': {
      id: '/_app/vocabulary/review'
      path: '/review'
      fullPath: '/vocabulary/review'
      preLoaderRoute: typeof AppVocabularyReviewRouteImport
      parentRoute: typeof AppVocabularyRoute
    }
    '/_app/songs/$id': {
      id: '/_app/songs/$id'
      path: '/songs/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof AppSongsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/$id': {
      id: '/_app/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof AppLessonsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dramas/$id': {
      id: '/_app/dramas/$id'
      path: '/dramas/$id'
      fullPath: '/dramas/$id'
      preLoaderRoute: typeof AppDramasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/curriculum/$id': {
      id: '/_app/curriculum/$id'
      path: '/curriculum/$id'
      fullPath: '/curriculum/$id'
      preLoaderRoute: typeof AppCurriculumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$id': {
      id: '/_app/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AppCoursesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/reengagement-push': {
      id: '/api/public/hooks/reengagement-push'
      path: '/api/public/hooks/reengagement-push'
      fullPath: '/api/public/hooks/reengagement-push'
      preLoaderRoute: typeof ApiPublicHooksReengagementPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-video': {
      id: '/api/public/hooks/generate-video'
      path: '/api/public/hooks/generate-video'
      fullPath: '/api/public/hooks/generate-video'
      preLoaderRoute: typeof ApiPublicHooksGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppVocabularyRouteChildren {
  AppVocabularyReviewRoute: typeof AppVocabularyReviewRoute
}

const AppVocabularyRouteChildren: AppVocabularyRouteChildren = {
  AppVocabularyReviewRoute: AppVocabularyReviewRoute,
}

const AppVocabularyRouteWithChildren = AppVocabularyRoute._addFileChildren(
  AppVocabularyRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppStudioRoute: typeof AppStudioRoute
  AppVocabularyRoute: typeof AppVocabularyRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCoursesIdRoute: typeof AppCoursesIdRoute
  AppCurriculumIdRoute: typeof AppCurriculumIdRoute
  AppDramasIdRoute: typeof AppDramasIdRoute
  AppLessonsIdRoute: typeof AppLessonsIdRoute
  AppSongsIdRoute: typeof AppSongsIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCurriculumIndexRoute: typeof AppCurriculumIndexRoute
  AppDramasIndexRoute: typeof AppDramasIndexRoute
  AppSongsIndexRoute: typeof AppSongsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppStudioRoute: AppStudioRoute,
  AppVocabularyRoute: AppVocabularyRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCoursesIdRoute: AppCoursesIdRoute,
  AppCurriculumIdRoute: AppCurriculumIdRoute,
  AppDramasIdRoute: AppDramasIdRoute,
  AppLessonsIdRoute: AppLessonsIdRoute,
  AppSongsIdRoute: AppSongsIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCurriculumIndexRoute: AppCurriculumIndexRoute,
  AppDramasIndexRoute: AppDramasIndexRoute,
  AppSongsIndexRoute: AppSongsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiYoutubeCallbackRoute: ApiYoutubeCallbackRoute,
  ApiYoutubeConnectRoute: ApiYoutubeConnectRoute,
  ApiPublicHooksGenerateVideoRoute: ApiPublicHooksGenerateVideoRoute,
  ApiPublicHooksReengagementPushRoute: ApiPublicHooksReengagementPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
